name: Auto Create PR from dev* to dev

on:
  push:
    branches:
      - 'dev*'

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.BE_REPO_TOKEN }} # Đảm bảo secret này vẫn đúng
          branch: ${{ github.ref_name }} 
          base: dev 
          title: "🚀 [Auto PR] Merge ${{ github.ref_name }} into dev"
          body: "Yêu cầu gộp code tự động từ Nguyễn Hoàng Đô."