name: Trigger Tests By Branch

on:
  pull_request:
    branches: [ "dev", "main" ]
    types: [opened, synchronize] 

  push:
    branches: [ "main", "master" ]

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Determine Event Type
        id: event_type
        run: |
          if [[ "${{ github.base_ref }}" == "main" || "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "type=run-full-regression-test" >> $GITHUB_OUTPUT
          else
            echo "type=run-smoke-test" >> $GITHUB_OUTPUT
          fi

      - name: 2. Send Signal to Cypress Repo
        run: |
          # Xác định mã SHA chuẩn: Nếu là PR thì lấy SHA của nhánh phụ, nếu là Push thì lấy SHA của commit
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            SHA="${{ github.event.pull_request.head.sha }}"
          else
            SHA="${{ github.sha }}"
          fi
          
          curl -X POST \
          -H "Authorization: token ${{ secrets.BE_REPO_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/hoangdotester/DoAnTotNghiep/dispatches \
          -d "{\"event_type\": \"${{ steps.event_type.outputs.type }}\", \"client_payload\": {\"sha\": \"$SHA\", \"repo\": \"${{ github.repository }}\"}}"