name: Trigger Tests By Branch

on:
  push:
    branches: [ "main", "master", "develop", "feature/*", "fix/*" ]

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Determine Event Type
        id: event_type
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" || "${{ github.ref }}" == "refs/heads/master" ]]; then
            echo "type=run-full-regression" >> $GITHUB_OUTPUT
          else
            echo "type=run-smoke-test" >> $GITHUB_OUTPUT
          fi

      - name: Send Signal to Cypress Repo
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.BE_REPO_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/hoangdotester/DoAnTotNghiep/dispatches \
          -d '{"event_type": "${{ steps.event_type.outputs.type }}"}'